name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build-linux:
    name: Build linux
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Build linux
      run:  go build -o polyglot main.go

    - name: Run tests
      run: go test ./cmd ./source ./language ./repository -v

    - name: Run polyglot
      run: ./polyglot --username=filhodanuvem --log=info

    - uses: actions/upload-artifact@master
      name: Generating artifact
      with:
        name: polyglot-linux64
        path: ./polyglot
